class GroceryProducts {
  int ?id;
  int quantity = 1;
  String? img, title;
  double ? price;

  GroceryProducts({this.id, this.img, this.title, this.price});

}

List<GroceryProducts> groceryProductsList = [
  GroceryProducts(id: 1,img: 'assets/images/grocery/egg2.png',
      title: 'Egg',
      price: 5.00),
  GroceryProducts(id: 2,img: 'assets/images/grocery/jhatpotchicken1.png',
      title: 'Jhotpot Chicken',
      price: 5.00),
  GroceryProducts(id: 3,img: 'assets/images/grocery/perrier.png',
      title: 'Perrier',
      price: 5.00),
  GroceryProducts(id: 4,img: 'assets/images/grocery/grandor1.png',
      title: 'Grandor',
      price: 5.00),
  GroceryProducts(id: 5,img: 'assets/images/grocery/mallaoplus1.png',
      title: 'Mallaw plus',
      price: 5.00),
  GroceryProducts(id: 6,img: 'assets/images/grocery/aquafina1.png',
      title: 'Aquafina',
      price: 5.00),
  GroceryProducts(id: 7,img: 'assets/images/grocery/filter1.png',
      title: 'Filter',
      price: 5.00),
  GroceryProducts(id: 8,img: 'assets/images/grocery/meatball1.png',
      title: 'Meat Ball',
      price: 5.00),
  GroceryProducts(id: 9,img: 'assets/images/grocery/trisha1.png',
      title: 'Trisa',
      price: 5.00),
  GroceryProducts(id: 10,img: 'assets/images/grocery/egg2.png',
      title: 'Egg',
      price: 5.00),
  GroceryProducts(id: 11,img: 'assets/images/grocery/jhatpotchicken1.png',
      title: 'Jhotpot Chicken',
      price: 5.00),
  GroceryProducts(id: 12,img: 'assets/images/grocery/perrier.png',
      title: 'Perrier',
      price: 5.00),

  GroceryProducts(id: 13,img: 'assets/images/grocery/egg2.png',
      title: 'Egg',
      price: 5.00),
  GroceryProducts(id: 14,img: 'assets/images/grocery/jhatpotchicken1.png',
      title: 'Jhotpot Chicken',
      price: 5.00),
  GroceryProducts(id: 15,img: 'assets/images/grocery/perrier.png',
      title: 'Perrier',
      price: 5.00),
  GroceryProducts(id: 16,img: 'assets/images/grocery/grandor1.png',
      title: 'Grandor',
      price: 5.00),
  GroceryProducts(id: 17,img: 'assets/images/grocery/mallaoplus1.png',
      title: 'Mallaw plus',
      price: 5.00),
  GroceryProducts(id: 18,img: 'assets/images/grocery/aquafina1.png',
      title: 'Aquafina',
      price: 5.00),
  GroceryProducts(id: 19,img: 'assets/images/grocery/filter1.png',
      title: 'Filter',
      price: 5.00),
  GroceryProducts(id: 20,img: 'assets/images/grocery/meatball1.png',
      title: 'Meat Ball',
      price: 5.00),
  GroceryProducts(id: 21,img: 'assets/images/grocery/trisha1.png',
      title: 'Trisa',
      price: 5.00),
  GroceryProducts(id: 22,img: 'assets/images/grocery/egg2.png',
      title: 'Egg',
      price: 5.00),
  GroceryProducts(id: 23,img: 'assets/images/grocery/jhatpotchicken1.png',
      title: 'Jhotpot Chicken',
      price: 5.00),
  GroceryProducts(id: 24,img: 'assets/images/grocery/perrier.png',
      title: 'Perrier',
      price: 5.00),

];